### ISSUE TITLE
addresses above 16

### ISSUE THREAD

**Issue by 242bpm** [mathertel/DMXSerial#50]
Hello!

Addressing channels 1-16 works like a charm for me! Addresses above don't (always on, always off, other strange behaviors).

I can reproduce this with all rgb led controllers i have from various manufacturers.

I'm using a Controllino Mega with a built in RS485 interface on Serial3.

I have patched the DMXSerial_avr.h with a definition for using Serial3:

```
#define UCSRnA UCSR3A
#define RXCn RXC3
#define TXCn TXC3
#define UCSRnB UCSR3B
#define RXCIEn RXCIE3
#define TXCIEn TXCIE3
#define UDRIEn UDRIE3
#define RXENn RXEN3
#define TXENn TXEN3
#define UCSRnC UCSR3C
#define USBSn USBS3
#define UCSZn0 UCSZ30
#define UPMn0 UPM30
#define UBRRnH UBRR3H
#define UBRRnL UBRR3L
#define UDRn UDR3
#define UDREn UDRE3
#define FEn FE3
#define USARTn_RX_vect USART3_RX_vect
#define USARTn_TX_vect USART3_TX_vect
#define USARTn_UDRE_vect USART3_UDRE_vect
```
Max channels is set to 64.
DMXSerial.maxChannel(64);

Any ideas, where i could have a look???

**Comment by mathertel** [comment]
I just doublechecked:
* The DMXSerialFlow example I use for sending out 60 * 3 RGB values.
* The DMXSerialRecv example I use on the device and get no problems above channel 36.
... work !
if you have flickering, that may be caused by missing a byte. as This may have multiple reasons you may need to look into the timing in more detail.
If you have a hint, just let me know.
